/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    DRT001: THREE.Mesh;
  };
  materials: {
    Orange: THREE.MeshStandardMaterial;
  };
};

export function DRT(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("./models/DRT.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DRT001.geometry}
        material={materials.Orange}
        position={[-1.089, -0.441, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("./models/DRT.gltf");
